- hosts: stock_servers
  become: yes
  gather_facts: true
  tasks:
    - name: Update all packages (Amazon Linux)
      ansible.builtin.yum:
        name: '*'
        state: latest
      when: ansible_facts['distribution'] in ['Amazon']

    - name: Install Git (Amazon Linux)
      ansible.builtin.yum:
        name: git
        state: present
      when: ansible_facts['distribution'] in ['Amazon']

    - name: Install tree (Amazon Linux)
      ansible.builtin.yum:
        name: tree
        state: present
      when: ansible_facts['distribution'] in ['Amazon']

    - name: Install pip (Amazon Linux)
      ansible.builtin.yum:
        name: python3-pip
        state: present
      when: ansible_facts['distribution'] in ['Amazon']

    - name: Install Docker from official repository
      ansible.builtin.shell: |
        amazon-linux-extras install docker
        systemctl start docker
        systemctl enable docker

    - name: Install Docker Compose from GitHub release
      ansible.builtin.shell: |
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
        ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

    - name: Create symbolic link for Docker Compose
      ansible.builtin.file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link
      when: ansible_facts['distribution'] in ['Amazon']

    - name: Verify Docker Compose installation
      ansible.builtin.command:
        cmd: docker-compose --version

    - name: Clone Git repository
      ansible.builtin.git:
        repo: 'https://github.com/Oreire/stock-price-app.git'
        dest: "{{ ansible_env.HOME }}/stock-price-app"
        version: 'main'

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
      when: ansible_facts['distribution'] in ['Amazon']

    - name: Start services using Docker Compose
      ansible.builtin.command:
        cmd: docker-compose up -d --build --force-recreate
        chdir: "{{ ansible_env.HOME }}/stock-price-app"
