---
- hosts: stock_servers
  become: yes
  gather_facts: true
  tasks:
    - name: Update all packages (Amazon Linux)
      ansible.builtin.yum:
        name: '*'
        state: latest
      when: ansible_facts['distribution'] in ['Amazon']

    - name: Install Git (Amazon Linux)
      ansible.builtin.yum:
        name: git
        state: present
      when: ansible_facts['distribution'] in ['Amazon']

    - name: Install tree (Amazon Linux)
      ansible.builtin.yum:
        name: tree
        state: present
      when: ansible_facts['distribution'] in ['Amazon']

    - name: Install pip (Amazon Linux)
      ansible.builtin.yum:
        name: python3-pip
        state: present
      when: ansible_facts['distribution'] in ['Amazon']

    - name: Downgrade docker package
      ansible.builtin.pip:
        name: docker==6.1.3
        state: present

    - name: Clone Git repository
      ansible.builtin.git:
        repo: 'https://github.com/Oreire/stock-price-app.git'
        dest: /home/{{ ansible_env.HOME }}/stock-price-app
        version: 'main'

    - name: Ensure Docker is installed (Amazon Linux)
      ansible.builtin.yum:
        name: docker
        state: present
      when: ansible_facts['distribution'] in ['Amazon']
    
    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
      when: ansible_facts['distribution'] in ['Amazon']

    - name: Ensure Docker Compose is installed
      ansible.builtin.pip:
        name: docker-compose
        extra_args: --ignore-installed requests
        state: present
      when: ansible_facts['distribution'] in ['Amazon']

    - name: Start services using Docker Compose
      ansible.builtin.command:
        cmd: docker-compose up -d --build --force-recreate
        chdir: /home/{{ ansible_env.HOME }}/stock-price-app

